### ISSUE TITLE
1.15.2 Port TODO

### ISSUE THREAD

**Issue by kulttuuri** [kulttuuri/quick-hotbar-mod#6]
Here are things that need to be done for port to 1.15.2 to compile:

- [ ] Change all Minecraft.getMinecraft() references to Minecraft.getInstance()
- [ ] Forge configuration handler (net.minecraftforge.common.config.Configuration) is now gone, need to port SettingsClient, SettingsServer, SettingsGlobal files. Port to new format. Some information about the removal and possible new files is [listed in this commit](https://github.com/MinecraftForge/MinecraftForge/commit/eb42614288d2397c2cdbfd294fb0ff0d5597b116#diff-ae834b007a44da09816951d5c6beedc7).
- [ ] Change all keyboard events to use LWJGL 3. Porting information is [here](https://gist.github.com/williewillus/353c872bcf1a6ace9921189f6100d09a). This shouldn't be too hard task.
- [ ] All Minecraft GUIs have changed quite a lot and they have been moved to widgets package. Port current GUIs to extend these new widgets and port to new format.
- [ ] Cannot find package import net.minecraftforge.fml.common.network.simpleimpl for Packets (for ex. file PacketAnnounceServerAssist) to work. Have they moved this package somewhere?
- [ ] net.minecraft.util.text.translation.I18n has been moved somewhere. Used in class TranslationHelper.
- [ ] A lot of minecraftforge imports for class QuickHotbarMod are missing. For example: net.minecraftforge.fml.common.Mod.EventHandler, net.minecraftforge.fml.common.Mod.Instance...
- [ ] Three minecraftforge packages for QuickHotbarEventHandlerServer have been moved somewhere else.
- [ ] Quite a lot of forge errors again in class QuickHotbarEventHandler.

**Comment by kulttuuri** [comment]
I feel like it would also make sense to first port to one or two older versions so there would only be one or two major changed things at a time. This would make the list seem much less overwhelming. Could also build older versions of the mod at the same time.
